# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |v|
    v.name = "apt_python_venv"
  end

  # If developing, you may want to uncomment the following.
  #   Not on by default because Guest additions required
  #   (extra installation step):
  # config.vm.synced_folder ".", "/home/vagrant/src"

  config.vm.provision "shell" do |p|
    p.inline = "/vagrant/setup.sh"
  end
end
